### ISSUE TITLE
Is it possible to clear other/all permissions?

### ISSUE THREAD

**Issue by absolutejam** [SNikalaichyk/cNtfsAccessControl#1]
Hi,

Is it possible to clear other/all permissions instead of choosing to remove individual principals? Is the functionality there to do the equivalent of 'Disable inheritance' -> 'Remove all inherited permissions from this object'?

I have certain folders that I want very specific NTFS permissions and this seems like the best way.

If this isn't something I'm overlooking, I'll try and dig in to the code.

Thanks!

**Comment by SNikalaichyk** [comment]
Hi,
It is not currently possible, but I will look into it. A new resource has to be created.

**Comment by SNikalaichyk** [comment]
The **cNtfsPermissionsInheritance** resource has been added. You can get it in the [dev](https://github.com/SNikalaichyk/cNtfsAccessControl/tree/dev) branch. Your feedback will be appreciated.

**Comment by absolutejam** [comment]
Hey, sorry for the delay.

This looks like exactly what I need. I was trying to write it myself, but I hadn't gotten to the grips with writing my own resources yet, but in seeing you create a new one has actually helped me understand a bit better.

Thanks for the help.

**Comment by SNikalaichyk** [comment]
Glad it helped. I am planning to release version 1.2 to PS Gallery within 2 weeks.
