### ISSUE TITLE
Support for Audit rules (SACLs)

### ISSUE THREAD

**Issue by mrhockeymonkey** [SNikalaichyk/cNtfsAccessControl#11]
Just a query really. I use this resource at work and it works great. A new requirement I have is to now look after some auditing rules. My first thought was to use this resource but it seems it does not support it. I've also been looking for alternatives such as [this](https://gallery.technet.microsoft.com/scriptcenter/PowerShellAccessControl-d3be7b83) and [this](https://www.powershellgallery.com/packages/AccessControlDSC/1.1.0.0) but they either lack support for the file system or I've been having issues getting them working reliably. 

Would there be any drive to include support for SACL's in this DSCResource  or do you recommend any other modules? If it turns out I have to write my own resource I'd be more than happy to contribute it here but only if you think its worth pursuing. 

Thanks

**Comment by SNikalaichyk** [comment]
Hi @mrhockeymonkey,
Thanks for your query! Although I haven't planned to add new functionality to this module, contributions are always welcome!
