### ISSUE TITLE
cNtfsAccessControl does not allow removal of unknown principals

### ISSUE THREAD

**Issue by jcwalker** [SNikalaichyk/cNtfsAccessControl#4]
@SNikalaichyk first off great module.  I am looking to use it harden servers.  Some of the policies I'm using require only specific principals to a be assigned to a file and if any principals that are not defined in the policy are found then this is a finding.  Has then been any talk of adding functionality that only assigns prinicpals defined in the configuration to a file/folder?  So if I write a configuration that says User1 has ReadWrite on C:\Folder it will give User1 the desired permissions and remove the principals not defined in the configuration.

**Comment by SNikalaichyk** [comment]
@jcwalker ,
Unfortunately there's currently no such functionality. Nevertheless, it's a great suggestion! 👍 Though it may be tricky to implement.
