### ISSUE TITLE
problem when NoPropagateInherit = $true

### ISSUE THREAD

**Issue by baldator** [SNikalaichyk/cNtfsAccessControl#5]
Hi,

I get the following message when applying the configuration with NoPropagateInherit = $true:

Cannot process argument transformation on parameter 'NoPropagateInherit'. Cannot convert value
"System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject]" to type "System.Boolean". Boolean
parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-FileSystemAccessRule

I've fixed the issue... I'm going to send you a pull request in order to submit the fixed version.

Thank you,
Marco

**Comment by jpuskar** [comment]
Same problem; just set `NoPropagateInherit = $true` on any example to repro.

**Comment by SNikalaichyk** [comment]
@baldator , @jpuskar ,
The bug fix has been released to the PS Gallery:
```powershell
Install-Module -Name cNtfsAccessControl -RequiredVersion 1.3.1
```
Thanks!
