### ISSUE TITLE
Set file/folder ownership?

### ISSUE THREAD

**Issue by Jackbennett** [SNikalaichyk/cNtfsAccessControl#7]
Could this module be extended to change ownership of files/folders?

**Comment by SNikalaichyk** [comment]
Hi @Jackbennett, at the moment I don't have such plans. Mostly because I am no longer actively using DSC, but this may change in future.

**Comment by Jackbennett** [comment]
Thanks for the quick response, I might get to make a PR in the future for it if I get things working.
